Mvc_Proje/Controllers/WriterMessageController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;

namespace Mvc_Proje.Controllers
{
    public class WriterMessageController : Controller
    {
        MessageManager _messageManager = new MessageManager(new EfMessageDal());
        MessageValidator messagevalidator = new MessageValidator();
        IHttpContextAccessor _httpContextAccessor;

        public WriterMessageController(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }

        //----------------------- GELEN KUTUSU -------------------------------------------
        
        public ActionResult Inbox(string p)
        {
            var writerEmail = _httpContextAccessor.HttpContext?.Session.GetString("WriterEmail");

            if (writerEmail == null)
            {
                return RedirectToAction("WriterLogin", "Login");
            }

            var messagelist = _messageManager.GetMessagesTake(writerEmail);
            return View(messagelist);
        }

        //-----------------------MESAJLAR PARTİAL VİEW-------------------------------------------

        public PartialViewResult MessageListMenu()
        {
            return PartialView();
        }

        //------------------------gİDEN MESAJLAR----------------------------------------------------

        public ActionResult Sendbox(string p)
        {
            var writerEmail = _httpContextAccessor.HttpContext?.Session.GetString("WriterEmail");

            if (writerEmail == null)
            {
                return RedirectToAction("WriterLogin", "Login");
            }

            var messagelist = _messageManager.GetMessagesSend(writerEmail);
            return View(messagelist);
        }

        //---------------------GELEN MESAJ DETAYLARI---------------------------------------------

        public ActionResult GetInboxDetail(int id)
        {
            var values = _messageManager.GetByID(id);
            return View(values);
        }

        //--------------------GİDEN MESAJ DETAYLARI----------------------------------------------

        public ActionResult GetSendboxDetails(int id)
        {
            var values = _messageManager.GetByID(id);
            return View(values);
        }

        //---------------------YENİ MESAJ EKLE---------------------------------------------

        [HttpGet]
        public ActionResult AddMessage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddMessage(Message p)
        {
            var writerEmail = _httpContextAccessor.HttpContext?.Session.GetString("WriterEmail");

            if (writerEmail == null)
            {
                return RedirectToAction("WriterLogin", "Login");
            }

            ValidationResult validationResult = messagevalidator.Validate(p);
            if (validationResult.IsValid)
            {
                p.MessageDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                _messageManager.MessageAdd(p);
                return RedirectToAction("Sendbox");
            }
            else
            {
                foreach (var item in validationResult.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

Mvc_Proje/Views/WriterMessage/AddMessage.cshtml
@model EntityLayer.Concrete.Message

@{
    ViewData["Title"] = "AddMessage";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Compose Message</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <!-- Theme style -->
    <!-- summernote -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">

    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition sidebar-mini">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1></h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @await Html.PartialAsync("MessageListMenu")
                <!-- /.col -->
                <div class="col-md-9">
                    @using (Html.BeginForm("AddMessage", "WriterMessage", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <div class="card card-primary card-outline">
                            <div class="card-header">
                                <h3 class="card-title">Mesaj Oluştur</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="form-group">
                                    @Html.Label("ReceiverMail", "Alıcı Mailini Girin", new { @class = "form-label fw-bold" })
                                    @Html.TextBoxFor(x => x.ReceiverMail, new { @class = "form-control rounded-pill" })
                                    @Html.ValidationMessageFor(x => x.ReceiverMail)@* 
                                    <input class="form-control" placeholder="ReceiverMail:" name="ReceiverMail"> *@
                                </div>
                                <div class="form-group">
                                    @Html.Label("Subject", "Bir Konu Girin", new { @class = "form-label fw-bold" })
                                    @Html.TextBoxFor(x => x.Subject, new { @class = "form-control rounded-pill" })
                                    @Html.ValidationMessageFor(x => x.Subject)
                                    @*  <input class="form-control" placeholder="Subject:" name="Subject"> *@
                                </div>
                                <div class="form-group">

                                    @Html.Label("MessageContent", "Mesajınızı Girin", new { @class = "form-label fw-bold" })
                                    <textarea name="MessageContent" id="compose-textarea" class="form-control" style="height: 300px">

                                        </textarea>
                                </div>
                                <div class="form-group">
                                    <div class="btn btn-default btn-file">
                                        <i class="fas fa-paperclip"></i> Dosya Ekle
                                        <input type="file" name="attachment">
                                    </div>
                                    <p class="help-block">Max. 32MB</p>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <div class="float-right">
                                    <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> İptal Et</button>
                                    <button type="submit" class="btn btn-primary"><i class="far fa-envelope"></i> Göner</button>
                                </div>

                            </div>
                            <!-- /.card-footer -->
                        </div>
                    }
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <!-- Summernote -->
    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- Page Script -->
    <script>
        $(function () {
            //Add text editor
            $('#compose-textarea').summernote()
          })</script>
</body>
</html>

Mvc_Proje/Views/WriterMessage/GetInboxDetail.cshtml
@model EntityLayer.Concrete.Message

@{
    ViewData["Title"] = "GetInboxDetail";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mesajlar</h1>
                </div>
            </div>
        </div>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">

                @await Html.PartialAsync("MessageListMenu")

                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Mesaj Detayları</h3>
                            <div class="card-tools">
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="mailbox-read-info">
                                <h5>Konu: @Html.DisplayFor(x => x.Subject)</h5>
                                <h6>
                                    Kimden: @Html.DisplayFor(x => x.SenderMail)
                                    <span class="mailbox-read-time float-right">@Model.MessageDate.ToShortDateString()</span>
                                </h6>
                            </div>
                            <!-- /.mailbox-read-info -->
                            <div class="mailbox-controls with-border text-center">
                            </div>
                            <!-- /.mailbox-controls -->
                            <div class="mailbox-read-message">
                                <p>@Html.DisplayFor(x => x.MessageContent)</p>
                            </div>
                            <!-- /.mailbox-read-message -->
                        </div>
                        <!-- /.card-footer -->
                    </div>
                    <button type="button" class="btn btn-warning" onclick="history.back()">Geri</button>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
    </section>
</body>
</html>

Mvc_Proje/Views/WriterMessage/GetSendboxDetails.cshtml
@{
    ViewData["Title"] = "GetSendboxDetails";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

@model EntityLayer.Concrete.Message

@{
    ViewData["Title"] = "GetSendboxDetails";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mesajlar</h1>
                </div>>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">

                @await Html.PartialAsync("MessageListMenu")

                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Mesaj Detayları</h3>
                            <div class="card-tools">
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="mailbox-read-info">
                                <h5>Konu: @Html.DisplayFor(x => x.Subject)</h5>
                                <h6>
                                    Kimden: @Html.DisplayFor(x => x.ReceiverMail)
                                    <span class="mailbox-read-time float-right">@Model.MessageDate.ToShortDateString()</span>
                                </h6>
                            </div>
                            <!-- /.mailbox-read-info -->
                            <div class="mailbox-controls with-border text-center">
                            </div>
                            <!-- /.mailbox-controls -->
                            <div class="mailbox-read-message">
                                <p>@Html.DisplayFor(x => x.MessageContent)</p>
                            </div>
                            <!-- /.mailbox-read-message -->
                        </div>
                        <!-- /.card-footer -->
                    </div>
                    <button type="button" class="btn btn-warning" onclick="history.back()">Geri</button>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
    </section>
</body>
</html>

Mvc_Proje/Views/WriterMessage/Inbox.cshtml
@using EntityLayer.Concrete
@model List<Message>

@{
    ViewData["Title"] = "Inbox";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">

            @await Html.PartialAsync("MessageListMenu")

            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Gelen Mesajlar</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Mesajlarda Ara">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                <div class="icheck-primary">
                                                    <input type="checkbox" value="" id="check1">
                                                    <label for="check1"></label>
                                                </div>
                                            </td>
                                            <td class="mailbox-star"><a href="/WriterMessage/GetInboxDetail/@item.MessageID/"><i class="fas fa-star text-warning"></i></a></td>
                                            <td class="mailbox-name"><a href="read-mail.html">@item.SenderMail</a></td>
                                            <td class="mailbox-subject">
                                                <b>@item.Subject</b> - @item.MessageContent
                                            </td>
                                            <td class="mailbox-attachment"></td>
                                            <td class="mailbox-date">
                                                @(((DateTime)item.MessageDate).ToString("dd-MMM-yyyy"))
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-0">
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

</body>
</html>

Mvc_Proje/Views/WriterMessage/MessageListMenu.cshtml
<div class="col-md-3">
    <a href="/WriterMessage/AddMessage/" class="btn btn-primary btn-block mb-3">Measaj Gönder</a>
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Seçenekler</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item active">
                    <a href="/WriterMessage/Inbox/" class="nav-link">
                        <i class="fas fa-inbox"></i> Gelen Mesajlar
                        <span class="badge bg-primary float-right">12</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/WriterMessage/Sendbox/" class="nav-link">
                        <i class="far fa-envelope"></i> Gönderilen Mesajlar
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="far fa-trash-alt"></i> Çöp Kutusu
                    </a>
                </li>
            </ul>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Diğer</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="far fa-circle text-danger"></i>
                        Birincil
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="far fa-circle text-warning"></i> Tanıtımlar
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="far fa-circle text-primary"></i>
                        Sosyal Medya
                    </a>
                </li>
            </ul>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>

Mvc_Proje/Views/WriterMessage/Sendbox.cshtml
@using EntityLayer.Concrete
@model List<Message>

@{
    ViewData["Title"] = "Sendbox";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">

            @await Html.PartialAsync("MessageListMenu")

            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Giden Mesajlar</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Mesajlarda Ara">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                <div class="icheck-primary">
                                                    <input type="checkbox" value="" id="check1">
                                                    <label for="check1"></label>
                                                </div>
                                            </td>
                                            <td class="mailbox-star"><a href="/WriterMessage/GetSendboxDetails/@item.MessageID/"><i class="fas fa-star text-warning"></i></a></td>
                                            <td class="mailbox-name"><a href="read-mail.html">@item.ReceiverMail</a></td>
                                            <td class="mailbox-subject">
                                                <b>@item.Subject</b> - @item.MessageContent
                                            </td>
                                            <td class="mailbox-attachment"></td>
                                            <td class="mailbox-date">
                                                @(((DateTime)item.MessageDate).ToString("dd-MMM-yyyy"))
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-0">
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

</body>
</html>